/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "communicate.h"
#include "article.h"
#include "subscribe.h"
#include "communication.h"

std::set<Subscriber> subs_list;

int *
join_1_svc(char *ip, int port,  struct svc_req *rqstp)
{
	static int  result;

	Subscriber sub(ip,port);
	subs_list.insert(sub);

	result =0;
	/*
	 * insert server code here
	 */

	return &result;
}

int *
leave_1_svc(char *ip, int port,  struct svc_req *rqstp)
{
	static int  result;
	Subscriber leaving_sub(ip, port);
	result = 1;

	auto client = subs_list.find(leaving_sub);
	if(client != subs_list.end()){
	  subs_list.erase(client);
	  result =0;
	}
	/*
	 * insert server code here
	 */

	return &result;
}

int *
subscribe_1_svc(char *ip, int port, char *article,  struct svc_req *rqstp)
{
	static int  result;
	Subscriber sub(ip, port);
	Article art(article);
	art.content = "";
	result =1 ;

	auto sub_it = subs_list.find(sub);
	if (sub_it != subs_list.end())
	  {
	    (*sub_it).articles.insert(art);
	    result = 0;
	  }


	/*
	 * insert server code here
	 */

	return &result;
}

int *
unsubscribe_1_svc(char *ip, int port, char *article,  struct svc_req *rqstp)
{
	static int  result;
	Subscriber sub(ip, port);
	Article art(article);
	result =1;

	auto sub_it = subs_list.find(sub);
	if (sub_it != subs_list.end())
	  {
	    if ((*sub_it).isSubs(art)) {

	      (*sub_it).unSubs(art);
	      result = 0;
	    }

	  }
	/*
	 * insert server code here
	 */

	return &result;
}

int *
publish_1_svc(char *article, char *ip, int port,  struct svc_req *rqstp)
{
	static int  result;
	Subscriber sub(ip, port);
	Article art(article);
	result =0;
	
	for (auto sub_it = subs_list.begin(); sub_it != subs_list.end(); ++sub_it)
	  {
	    if ((*sub_it).isSubs(art))
	      {
		send_client((*sub_it), article);
	      }
	  }
	/*

	 * insert server code here
	 */

	return &result;
}

int *
ping_1_svc(struct svc_req *rqstp)
{
	static int  result;

	result =0;
	/*
	 * insert server code here
	 */

	return &result;
}
