/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "communicate.h"

bool_t
xdr_ip (XDR *xdrs, ip *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAX_LENGTH))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_article (XDR *xdrs, article *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXSTRING))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_join_1_argument (XDR *xdrs, join_1_argument *objp)
{
	 if (!xdr_ip (xdrs, &objp->IP))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->Port))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_leave_1_argument (XDR *xdrs, leave_1_argument *objp)
{
	 if (!xdr_ip (xdrs, &objp->IP))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->Port))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_subscribe_1_argument (XDR *xdrs, subscribe_1_argument *objp)
{
	 if (!xdr_ip (xdrs, &objp->IP))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->Port))
		 return FALSE;
	 if (!xdr_article (xdrs, &objp->Article))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_unsubscribe_1_argument (XDR *xdrs, unsubscribe_1_argument *objp)
{
	 if (!xdr_ip (xdrs, &objp->IP))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->Port))
		 return FALSE;
	 if (!xdr_article (xdrs, &objp->Article))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_publish_1_argument (XDR *xdrs, publish_1_argument *objp)
{
	 if (!xdr_article (xdrs, &objp->Article))
		 return FALSE;
	 if (!xdr_ip (xdrs, &objp->IP))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->Port))
		 return FALSE;
	return TRUE;
}
