/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _COMMUNICATE_H_RPCGEN
#define _COMMUNICATE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXSTRING 12
#define MAX_LENGTH 15

typedef char *ip;

typedef char *article;

struct trig {
	int port;
	ip addr;
};
typedef struct trig trig;

struct pub {
	article art;
	ip addr;
	int port;
};
typedef struct pub pub;

struct sub {
	ip addr;
	int port;
	article arti;
};
typedef struct sub sub;

#define COMMUNICATE_PROG 0x42424242
#define COMMUNICATE_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define JOIN 1
extern  bool_t * join_1(trig *, CLIENT *);
extern  bool_t * join_1_svc(trig *, struct svc_req *);
#define LEAVE 2
extern  bool_t * leave_1(trig *, CLIENT *);
extern  bool_t * leave_1_svc(trig *, struct svc_req *);
#define SUBSCRIBE 3
extern  bool_t * subscribe_1(sub *, CLIENT *);
extern  bool_t * subscribe_1_svc(sub *, struct svc_req *);
#define UNSUBSCRIBE 4
extern  bool_t * unsubscribe_1(sub *, CLIENT *);
extern  bool_t * unsubscribe_1_svc(sub *, struct svc_req *);
#define PUBLISH 5
extern  bool_t * publish_1(pub *, CLIENT *);
extern  bool_t * publish_1_svc(pub *, struct svc_req *);
#define PING 6
extern  bool_t * ping_1(void *, CLIENT *);
extern  bool_t * ping_1_svc(void *, struct svc_req *);
extern int communicate_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define JOIN 1
extern  bool_t * join_1();
extern  bool_t * join_1_svc();
#define LEAVE 2
extern  bool_t * leave_1();
extern  bool_t * leave_1_svc();
#define SUBSCRIBE 3
extern  bool_t * subscribe_1();
extern  bool_t * subscribe_1_svc();
#define UNSUBSCRIBE 4
extern  bool_t * unsubscribe_1();
extern  bool_t * unsubscribe_1_svc();
#define PUBLISH 5
extern  bool_t * publish_1();
extern  bool_t * publish_1_svc();
#define PING 6
extern  bool_t * ping_1();
extern  bool_t * ping_1_svc();
extern int communicate_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_ip (XDR *, ip*);
extern  bool_t xdr_article (XDR *, article*);
extern  bool_t xdr_trig (XDR *, trig*);
extern  bool_t xdr_pub (XDR *, pub*);
extern  bool_t xdr_sub (XDR *, sub*);

#else /* K&R C */
extern bool_t xdr_ip ();
extern bool_t xdr_article ();
extern bool_t xdr_trig ();
extern bool_t xdr_pub ();
extern bool_t xdr_sub ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_COMMUNICATE_H_RPCGEN */
