/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _COMMUNICATE_H_RPCGEN
#define _COMMUNICATE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXSTRING 120
#define MAX_LENGTH 15

typedef char *ip;

typedef char *article;

struct join_1_argument {
	ip IP;
	int Port;
};
typedef struct join_1_argument join_1_argument;

struct leave_1_argument {
	ip IP;
	int Port;
};
typedef struct leave_1_argument leave_1_argument;

struct subscribe_1_argument {
	ip IP;
	int Port;
	article Article;
};
typedef struct subscribe_1_argument subscribe_1_argument;

struct unsubscribe_1_argument {
	ip IP;
	int Port;
	article Article;
};
typedef struct unsubscribe_1_argument unsubscribe_1_argument;

struct publish_1_argument {
	article Article;
	ip IP;
	int Port;
};
typedef struct publish_1_argument publish_1_argument;

#define COMMUNICATE_PROG 0x42424242
#define COMMUNICATE_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define JOIN 1
extern  bool_t * join_1(ip , int , CLIENT *);
extern  bool_t * join_1_svc(ip , int , struct svc_req *);
#define LEAVE 2
extern  bool_t * leave_1(ip , int , CLIENT *);
extern  bool_t * leave_1_svc(ip , int , struct svc_req *);
#define SUBSCRIBE 3
extern  bool_t * subscribe_1(ip , int , article , CLIENT *);
extern  bool_t * subscribe_1_svc(ip , int , article , struct svc_req *);
#define UNSUBSCRIBE 4
extern  bool_t * unsubscribe_1(ip , int , article , CLIENT *);
extern  bool_t * unsubscribe_1_svc(ip , int , article , struct svc_req *);
#define PUBLISH 5
extern  bool_t * publish_1(article , ip , int , CLIENT *);
extern  bool_t * publish_1_svc(article , ip , int , struct svc_req *);
#define PING 6
extern  bool_t * ping_1(CLIENT *);
extern  bool_t * ping_1_svc(struct svc_req *);
extern int communicate_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define JOIN 1
extern  bool_t * join_1();
extern  bool_t * join_1_svc();
#define LEAVE 2
extern  bool_t * leave_1();
extern  bool_t * leave_1_svc();
#define SUBSCRIBE 3
extern  bool_t * subscribe_1();
extern  bool_t * subscribe_1_svc();
#define UNSUBSCRIBE 4
extern  bool_t * unsubscribe_1();
extern  bool_t * unsubscribe_1_svc();
#define PUBLISH 5
extern  bool_t * publish_1();
extern  bool_t * publish_1_svc();
#define PING 6
extern  bool_t * ping_1();
extern  bool_t * ping_1_svc();
extern int communicate_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_ip (XDR *, ip*);
extern  bool_t xdr_article (XDR *, article*);
extern  bool_t xdr_join_1_argument (XDR *, join_1_argument*);
extern  bool_t xdr_leave_1_argument (XDR *, leave_1_argument*);
extern  bool_t xdr_subscribe_1_argument (XDR *, subscribe_1_argument*);
extern  bool_t xdr_unsubscribe_1_argument (XDR *, unsubscribe_1_argument*);
extern  bool_t xdr_publish_1_argument (XDR *, publish_1_argument*);

#else /* K&R C */
extern bool_t xdr_ip ();
extern bool_t xdr_article ();
extern bool_t xdr_join_1_argument ();
extern bool_t xdr_leave_1_argument ();
extern bool_t xdr_subscribe_1_argument ();
extern bool_t xdr_unsubscribe_1_argument ();
extern bool_t xdr_publish_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_COMMUNICATE_H_RPCGEN */
